# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/python-app.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        # os: ['ubuntu-latest']
        python-version: [3.5, 3.8, 3.9]
        # python-version: [3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run test
      shell: pwsh
      run: |
        ./mqtt_monitor.py --conf mqtt_monitor.conf.sample  --test
